FROM  mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR apiCqrs

EXPOSE 80
EXPOSE 5000

COPY ./*.csproj ./

RUN dotnet restore


COPY . .
RUN dotnet publish -c Release -o out


FROM  mcr.microsoft.com/dotnet/sdk:6.0
WORKDIR /apiCqrs
COPY --from=build /apiCqrs/out
ENTRYPOINT ["dotnet", "CQRS.Ejemplo.dll"]